import { StyleSheet, Platform } from 'react-native';

export const styles = StyleSheet.create({
  container: {
    flex: 1,
    backgroundColor: '#121212',
  },
  overlay: {
    flex: 1,
    backgroundColor: 'rgba(0, 0, 0, 0.3)',
  },
  content: {
    flexGrow: 1,
    paddingHorizontal: 24,
    paddingTop: Platform.OS === 'android' ? 100 : 60,
    paddingBottom: 40,
  },
  headerContainer: {
    marginTop: 40,
    marginBottom: 40,
    alignItems: 'center',
  },
  title: {
    fontSize: 46,
    fontWeight: '800',
    color: '#ffffff',
    letterSpacing: 1.5,
    textShadowColor: 'rgba(0, 0, 0, 0.3)',
    textShadowOffset: { width: 0, height: 2 },
    textShadowRadius: 4,
  },
  subtitle: {
    fontSize: 26,
    fontWeight: '300',
    color: '#e0e0e0',
    letterSpacing: 4,
  },
  controlsContainer: {
    width: '100%',
    marginBottom: 20,
  },
  searchContainer: {
    flexDirection: 'row',
    backgroundColor: 'rgba(255, 255, 255, 0.15)',
    borderRadius: 16,
    borderWidth: 1,
    borderColor: 'rgba(255, 255, 255, 0.3)',
    marginBottom: 16,
    overflow: 'hidden',
    height: 55,
  },
  searchInput: {
    flex: 1,
    color: '#ffffff',
    paddingHorizontal: 16,
    fontSize: 16,
  },
  searchButton: {
    paddingHorizontal: 16,
    justifyContent: 'center',
    alignItems: 'center',
    backgroundColor: 'rgba(255, 255, 255, 0.1)',
  },
  searchIcon: {
    fontSize: 18,
  },
  suggestionsContainer: {
    backgroundColor: 'rgba(20, 20, 20, 0.85)',
    borderRadius: 12,
    marginTop: -10,
    marginBottom: 20,
    padding: 10,
    borderWidth: 1,
    borderColor: 'rgba(255, 255, 255, 0.2)',
  },
  suggestionItem: {
    paddingVertical: 12,
    borderBottomWidth: 1,
    borderBottomColor: 'rgba(255, 255, 255, 0.1)',
  },
  suggestionText: {
    color: '#fff',
    fontSize: 16,
  },
  favoritesContainer: {
    marginBottom: 20,
  },
  favoritesTitle: {
    color: '#fff',
    fontSize: 16,
    fontWeight: '600',
    marginBottom: 10,
  },
  favoriteChip: {
    backgroundColor: 'rgba(255, 255, 255, 0.2)',
    paddingVertical: 8,
    paddingHorizontal: 16,
    borderRadius: 20,
    marginRight: 10,
    borderWidth: 1,
    borderColor: 'rgba(255, 255, 255, 0.3)',
  },
  favoriteChipText: {
    color: '#fff',
    fontWeight: '600',
  },
  dividerContainer: {
    flexDirection: 'row',
    alignItems: 'center',
    marginVertical: 20,
  },
  divider: {
    flex: 1,
    height: 1,
    backgroundColor: 'rgba(255, 255, 255, 0.3)',
  },
  dividerText: {
    color: 'rgba(255, 255, 255, 0.7)',
    marginHorizontal: 15,
    fontSize: 14,
    fontWeight: '600',
  },
  secondaryButton: {
    backgroundColor: 'rgba(0, 0, 0, 0.4)',
    paddingVertical: 16,
    borderRadius: 16,
    borderWidth: 1,
    borderColor: 'rgba(255, 255, 255, 0.2)',
    alignItems: 'center',
  },
  secondaryButtonText: {
    color: '#ffffff',
    fontSize: 16,
    fontWeight: '600',
    letterSpacing: 0.5,
  },
  loadingContainer: {
    alignItems: 'center',
    justifyContent: 'center',
    marginTop: 20,
    marginBottom: 20,
  },
  loadingText: {
    color: '#ffffff',
    marginTop: 12,
    fontSize: 16,
    fontWeight: '500',
  },
  weatherDetailsContainer: {
    width: '100%',
    alignItems: 'center',
    marginTop: 0,
  },
  absoluteBackButton: {
    position: 'absolute',
    top: Platform.OS === 'android' ? 25 : 45,
    left: 15,
    zIndex: 10,
    padding: 10,
  },
  backButtonText: {
    color: '#ffffff',
    fontSize: 28,
    fontWeight: '700',
    textShadowColor: 'rgba(0, 0, 0, 0.5)',
    textShadowOffset: { width: 0, height: 1 },
    textShadowRadius: 3,
  },
  absoluteUnitButton: {
    position: 'absolute',
    top: Platform.OS === 'android' ? 50 : 45,
    right: 55,
    zIndex: 10,
    padding: 4,
    backgroundColor: 'rgba(0, 0, 0, 0.4)',
    borderRadius: 16,
    minWidth: 32,
    height: 32,
    alignItems: 'center',
    justifyContent: 'center',
  },
  unitButtonText: {
    color: '#ffffff',
    fontSize: 14,
    fontWeight: '700',
  },
  absoluteSettingsButton: {
    position: 'absolute',
    top: Platform.OS === 'android' ? 50 : 45,
    right: 95,
    zIndex: 10,
    padding: 4,
    backgroundColor: 'rgba(0, 0, 0, 0.4)',
    borderRadius: 16,
    width: 32,
    height: 32,
    alignItems: 'center',
    justifyContent: 'center',
  },
  settingsIcon: {
    fontSize: 16,
  },
  absoluteFavButton: {
    position: 'absolute',
    top: Platform.OS === 'android' ? 50 : 45,
    right: 15,
    zIndex: 10,
    padding: 4,
    width: 32,
    height: 32,
    alignItems: 'center',
    justifyContent: 'center',
  },
  absoluteFavIcon: {
    width: 22,
    height: 22,
    tintColor: '#ffffff',
  },
  resultBox: {
    backgroundColor: 'rgba(10, 15, 25, 0.65)',
    borderRadius: 36,
    paddingVertical: 16,
    paddingHorizontal: 20,
    alignItems: 'center',
    borderWidth: 1,
    borderColor: 'rgba(255, 255, 255, 0.12)',
    shadowColor: '#000',
    shadowOffset: { width: 0, height: 15 },
    shadowOpacity: 0.4,
    shadowRadius: 20,
    elevation: 10,
    marginTop: 0,
    width: '95%',
  },
  resultCity: {
    fontSize: 28,
    fontWeight: '800',
    color: '#ffffff',
    textAlign: 'center',
    letterSpacing: 1,
    textShadowColor: 'rgba(0, 0, 0, 0.4)',
    textShadowOffset: { width: 0, height: 2 },
    textShadowRadius: 4,
  },
  resultCondition: {
    fontSize: 16,
    fontWeight: '500',
    color: 'rgba(255, 255, 255, 0.85)',
    textTransform: 'uppercase',
    letterSpacing: 2,
    marginTop: 0,
    marginBottom: 0,
  },
  tempContainer: {
    marginVertical: 0,
  },
  resultTemp: {
    fontSize: 90,
    fontWeight: '100',
    color: '#ffffff',
    textShadowColor: 'rgba(0, 0, 0, 0.2)',
    textShadowOffset: { width: 0, height: 4 },
    textShadowRadius: 8,
    includeFontPadding: false,
    lineHeight: 95,
  },
  detailsGrid: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    width: '100%',
    marginTop: 0,
    paddingTop: 15,
    borderTopWidth: 1,
    borderTopColor: 'rgba(255, 255, 255, 0.2)',
  },
  sunGrid: {
    width: '95%',
    marginTop: 15,
    paddingVertical: 20,
    backgroundColor: 'rgba(10, 15, 25, 0.65)',
    borderRadius: 24,
    borderWidth: 1,
    borderColor: 'rgba(255, 255, 255, 0.12)',
  },
  detailItem: {
    alignItems: 'center',
    flex: 1,
  },
  sunItem: {
    alignItems: 'center',
    flex: 1,
  },
  detailIcon: {
    fontSize: 24,
    marginBottom: 8,
  },
  detailLabel: {
    fontSize: 12,
    color: 'rgba(255, 255, 255, 0.8)',
    textTransform: 'uppercase',
    fontWeight: '600',
    marginBottom: 4,
    letterSpacing: 0.5,
  },
  detailValue: {
    fontSize: 17,
    fontWeight: 'bold',
    color: '#ffffff',
  },
  forecastContainer: {
    marginTop: 15,
    marginBottom: 20,
    width: '95%',
    backgroundColor: 'rgba(10, 15, 25, 0.65)',
    borderRadius: 24,
    paddingVertical: 20,
    paddingHorizontal: 20,
    borderWidth: 1,
    borderColor: 'rgba(255, 255, 255, 0.12)',
  },
  forecastTitle: {
    color: 'rgba(255, 255, 255, 0.8)',
    fontSize: 14,
    fontWeight: '600',
    textTransform: 'uppercase',
    marginBottom: 15,
    letterSpacing: 1,
  },
  forecastItem: {
    alignItems: 'center',
    marginRight: 15,
    backgroundColor: 'rgba(255, 255, 255, 0.15)',
    paddingVertical: 12,
    paddingHorizontal: 16,
    borderRadius: 16,
    borderWidth: 1,
    borderColor: 'rgba(255, 255, 255, 0.2)',
  },
  forecastTime: {
    color: '#e0e0e0',
    fontSize: 14,
    marginBottom: 8,
    fontWeight: '500',
  },
  forecastTemp: {
    color: '#ffffff',
    fontSize: 20,
    fontWeight: '700',
  },
  dailyForecastContainer: {
    marginBottom: 20,
    width: '95%',
    backgroundColor: 'rgba(10, 15, 25, 0.65)',
    borderRadius: 24,
    paddingVertical: 20,
    paddingHorizontal: 20,
    borderWidth: 1,
    borderColor: 'rgba(255, 255, 255, 0.12)',
  },
  dailyForecastItem: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    paddingVertical: 12,
    borderBottomWidth: 1,
    borderBottomColor: 'rgba(255, 255, 255, 0.1)',
  },
  dailyForecastDay: {
    color: '#e0e0e0',
    fontSize: 16,
    fontWeight: '600',
    width: 60,
  },
  dailyForecastIconContainer: {
    flex: 1,
    alignItems: 'center',
  },
  dailyForecastTempContainer: {
    flexDirection: 'row',
    alignItems: 'center',
    width: 80,
    justifyContent: 'flex-end',
  },
  dailyForecastMax: {
    color: '#ffffff',
    fontSize: 16,
    fontWeight: '700',
    marginRight: 10,
  },
  dailyForecastMin: {
    color: 'rgba(255, 255, 255, 0.6)',
    fontSize: 16,
    fontWeight: '600',
  },
  insightsContainer: {
    flexDirection: 'row',
    alignItems: 'center',
    marginTop: 20,
    paddingTop: 15,
    borderTopWidth: 1,
    borderTopColor: 'rgba(255, 255, 255, 0.2)',
    width: '100%',
  },
  insightsIcon: {
    fontSize: 24,
    marginRight: 10,
  },
  insightsText: {
    flex: 1,
    color: '#e0e0e0',
    fontSize: 14,
    fontStyle: 'italic',
    lineHeight: 20,
  },
  sunRow: {
    flexDirection: 'row',
    justifyContent: 'space-around',
    width: '100%',
  },
  arcContainer: {
    width: '80%',
    height: 30,
    marginTop: 20,
    position: 'relative',
    alignSelf: 'center',
  },
  arcLine: {
    position: 'absolute',
    top: 15,
    left: 0,
    right: 0,
    height: 2,
    backgroundColor: 'rgba(255, 255, 255, 0.3)',
    borderRadius: 1,
  },
  sunDot: {
    position: 'absolute',
    top: 3,
    marginLeft: -10,
  },
  moonContainer: {
    alignItems: 'center',
    marginTop: 15,
    borderTopWidth: 1,
    borderTopColor: 'rgba(255, 255, 255, 0.1)',
    paddingTop: 15,
    width: '80%',
    alignSelf: 'center',
  },
  modalOverlay: {
    flex: 1,
    justifyContent: 'flex-end',
    backgroundColor: 'rgba(0, 0, 0, 0.5)',
  },
  modalContent: {
    backgroundColor: '#1e1e1e',
    borderTopLeftRadius: 24,
    borderTopRightRadius: 24,
    borderBottomLeftRadius: 0,
    borderBottomRightRadius: 0,
    width: '100%',
    paddingTop: 24,
    paddingHorizontal: 24,
    paddingBottom: 160,
    minHeight: 250,
    marginBottom: -100,
  },
  modalHeader: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    marginBottom: 20,
  },
  modalTitle: {
    color: '#fff',
    fontSize: 20,
    fontWeight: 'bold',
  },
  modalCloseText: {
    color: '#fff',
    fontSize: 24,
    padding: 5,
  },
  settingRow: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    paddingVertical: 15,
    borderBottomWidth: 1,
    borderBottomColor: 'rgba(255, 255, 255, 0.1)',
  },
  settingLabel: {
    color: '#fff',
    fontSize: 16,
  },
  langButtonsRow: {
    flexDirection: 'row',
    flexWrap: 'wrap',
    justifyContent: 'flex-end',
    width: '60%',
  },
  langBtn: {
    paddingVertical: 6,
    paddingHorizontal: 12,
    borderRadius: 12,
    borderWidth: 1,
    borderColor: 'rgba(255,255,255,0.3)',
    marginLeft: 8,
    marginBottom: 8,
  },
  langBtnActive: {
    backgroundColor: '#81b0ff',
    borderColor: '#81b0ff',
  },
  langBtnText: {
    color: 'rgba(255,255,255,0.6)',
    fontSize: 14,
    fontWeight: 'bold',
  },
  langBtnTextActive: {
    color: '#121212',
  },
  extraMetricsGrid: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    width: '100%',
    marginTop: 15,
    paddingTop: 15,
    borderTopWidth: 1,
    borderTopColor: 'rgba(255, 255, 255, 0.2)',
  },
  aqiContainer: {
    flex: 1,
    alignItems: 'center',
    marginRight: 10,
  },
  aqiBar: {
    width: '100%',
    height: 8,
    backgroundColor: 'rgba(255, 255, 255, 0.2)',
    borderRadius: 4,
    marginVertical: 8,
    overflow: 'hidden',
  },
  aqiFill: {
    height: '100%',
    borderRadius: 4,
  },
  thermometerContainer: {
    flex: 1,
    alignItems: 'center',
    marginLeft: 10,
  },
  thermoBar: {
    width: '100%',
    height: 8,
    backgroundColor: 'rgba(255, 255, 255, 0.2)',
    borderRadius: 4,
    marginVertical: 8,
    overflow: 'hidden',
    justifyContent: 'center',
  },
  thermoFill: {
    height: '100%',
    borderRadius: 4,
  },
  triviaContainer: {
    marginBottom: 20,
    width: '95%',
    backgroundColor: 'rgba(10, 15, 25, 0.85)',
    borderRadius: 16,
    paddingVertical: 16,
    paddingHorizontal: 20,
    borderWidth: 1,
    borderColor: 'rgba(255, 255, 255, 0.3)',
    alignItems: 'center',
  },
  triviaTitle: {
    color: '#026ec1',
    fontSize: 14,
    fontWeight: '700',
    textTransform: 'uppercase',
    marginBottom: 8,
    letterSpacing: 1,
  },
  triviaText: {
    color: '#e0e0e0',
    fontSize: 15,
    fontStyle: 'italic',
    textAlign: 'center',
    lineHeight: 22,
  },
  ootdContainer: {
    backgroundColor: 'rgba(10, 15, 25, 0.85)',
    borderRadius: 16,
    padding: 20,
    marginBottom: 20,
    width: '95%',
    alignSelf: 'center',
    borderWidth: 1,
    borderColor: 'rgba(255, 255, 255, 0.3)',
  },
  ootdTitle: {
    color: '#026ec1',
    fontSize: 16,
    fontWeight: '700',
    marginBottom: 10,
    textTransform: 'uppercase',
  },
  ootdText: {
    color: '#e0e0e0',
    fontSize: 15,
    lineHeight: 22,
  },
  actionButtonsContainer: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    marginBottom: 20,
    width: '95%',
    alignSelf: 'center',
  },
  actionButton: {
    flex: 1,
    backgroundColor: 'rgba(10, 15, 25, 0.85)',
    borderRadius: 16,
    padding: 15,
    marginHorizontal: 5,
    alignItems: 'center',
    flexDirection: 'row',
    justifyContent: 'center',
    borderWidth: 1,
    borderColor: 'rgba(255, 255, 255, 0.3)',
  },
  actionButtonIcon: {
    fontSize: 18,
    marginRight: 8,
  },
  actionButtonText: {
    color: '#fff',
    fontSize: 14,
    fontWeight: '600',
  },
  triviaQuestion: {
    color: '#ffffff',
    fontSize: 16,
    fontWeight: '600',
    marginBottom: 15,
    textAlign: 'center',
  },
  triviaOptionsContainer: {
    width: '100%',
  },
  triviaOptionBtn: {
    backgroundColor: 'rgba(255, 255, 255, 0.15)',
    padding: 12,
    borderRadius: 8,
    marginBottom: 8,
    borderWidth: 1,
    borderColor: 'rgba(255, 255, 255, 0.2)',
  },
  triviaOptionText: {
    color: '#fff',
    textAlign: 'center',
    fontSize: 14,
  },
  moodContainer: {
    marginBottom: 20,
    width: '95%',
    backgroundColor: 'rgba(10, 15, 25, 0.85)',
    borderRadius: 16,
    paddingVertical: 16,
    paddingHorizontal: 20,
    borderWidth: 1,
    borderColor: 'rgba(255, 255, 255, 0.3)',
    alignItems: 'center',
    alignSelf: 'center',
  },
  moodTitle: {
    color: '#fff',
    fontSize: 16,
    fontWeight: '600',
    marginBottom: 15,
  },
  moodButtonsRow: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    width: '100%',
  },
  moodBtn: {
    alignItems: 'center',
    padding: 10,
    backgroundColor: 'rgba(255, 255, 255, 0.1)',
    borderRadius: 12,
    width: '22%',
  },
  moodEmoji: {
    fontSize: 24,
    marginBottom: 4,
  },
  moodBtnText: {
    color: '#e0e0e0',
    fontSize: 12,
  },
  engagementBtn: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'center',
    paddingVertical: 10,
    width: '100%',
  },
  engagementBtnText: {
    color: '#fff',
    fontSize: 16,
    fontWeight: '600',
  },
  badgesGrid: {
    flexDirection: 'row',
    flexWrap: 'wrap',
    justifyContent: 'space-around',
    width: '100%',
    marginTop: 20,
  },
  badgeItem: {
    alignItems: 'center',
    width: '45%',
    marginBottom: 20,
    padding: 15,
    backgroundColor: 'rgba(255, 255, 255, 0.1)',
    borderRadius: 16,
    borderWidth: 1,
    borderColor: 'rgba(255, 255, 255, 0.2)',
  },
  badgeLocked: {
    opacity: 0.4,
  },
  badgeName: {
    color: '#fff',
    marginTop: 8,
    fontWeight: '600',
    fontSize: 14,
    textAlign: 'center',
  },
  moodHistoryItem: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    paddingVertical: 12,
    borderBottomWidth: 1,
    borderBottomColor: 'rgba(255, 255, 255, 0.1)',
    width: '100%',
    paddingHorizontal: 10,
  },
  moodHistoryDate: {
    color: '#fff',
    fontWeight: '500',
  },
  moodHistoryMood: {
    color: '#e0e0e0',
  },
  pulseContainer: {
    marginBottom: 20,
    width: '95%',
    backgroundColor: 'rgba(59, 130, 246, 0.15)',
    borderRadius: 16,
    paddingVertical: 16,
    paddingHorizontal: 20,
    borderWidth: 1,
    borderColor: 'rgba(59, 130, 246, 0.3)',
    alignItems: 'center',
    alignSelf: 'center',
  },
  pulseTitle: {
    color: '#93c5fd',
    fontSize: 15,
    fontWeight: '700',
    textTransform: 'uppercase',
  },
  pulseText: {
    color: '#e0e0e0',
    fontSize: 15,
    fontStyle: 'italic',
    textAlign: 'center',
    lineHeight: 22,
  },
  explorerList: {
    paddingVertical: 10,
  },
  explorerItem: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    paddingVertical: 15,
    borderBottomWidth: 1,
    borderBottomColor: 'rgba(255,255,255,0.1)',
  },
  explorerItemText: {
    color: '#fff',
    fontSize: 16,
  },
  explorerItemIcon: {
    color: '#888',
    fontSize: 16,
  },
  deepDiveContainer: {
    paddingVertical: 10,
  },
  deepDiveBadge: {
    padding: 10,
    borderRadius: 8,
    alignItems: 'center',
    marginBottom: 20,
  },
  deepDiveAqiText: {
    fontSize: 16,
    fontWeight: 'bold',
  },
  deepDiveSectionTitle: {
    color: '#93c5fd',
    fontSize: 14,
    textTransform: 'uppercase',
    marginBottom: 15,
  },
  pollutantRow: {
    flexDirection: 'row',
    alignItems: 'center',
    marginBottom: 12,
  },
  pollutantName: {
    color: '#fff',
    width: 60,
    fontSize: 12,
  },
  pollutantBarBg: {
    flex: 1,
    height: 8,
    backgroundColor: 'rgba(255,255,255,0.1)',
    borderRadius: 4,
    marginHorizontal: 10,
    overflow: 'hidden',
  },
  pollutantBarFill: {
    height: '100%',
    borderRadius: 4,
  },
  pollutantValue: {
    color: '#fff',
    width: 40,
    textAlign: 'right',
    fontSize: 12,
  },
  deepDiveAdvice: {
    color: '#026ec1',
    marginTop: 20,
    fontStyle: 'italic',
    textAlign: 'center',
  },
});
